test

diff --git a/.github/workflows/version-check.yml b/.github/workflows/version-check.yml
--- a/.github/workflows/version-check.yml
+++ b/.github/workflows/version-check.yml
@@ -14,9 +14,14 @@ jobs:
 
       - name: Check if Documentation is Updated
         run: |
-          if git diff --name-only HEAD~1 HEAD | grep -q '^docs/'; then
-            echo "Documentation updated."
-          else
-            echo "::error::Documentation in 'docs/' folder is not updated! Please update documentation before committing."
-            exit 1
-          fi
+            if git rev-parse --verify HEAD~1 >/dev/null 2>&1; then
+                DIFF_TARGET="HEAD~1"
+            else
+                DIFF_TARGET="origin/main"
+            fi
+            if git diff --name-only $DIFF_TARGET HEAD | grep -q '^docs/'; then
+                echo "Documentation updated."
+            else
+                echo "::error::Documentation in 'docs/' folder is not updated! Please update documentation before committing."
+                exit 1
+            fi
